USE customer_behaviour ;
-- Q1. What is the total revenue generated by male vs. female customers
SELECT 
Gender , 
SUM(purchase_amount ) AS Revenue 
FROM sales.shopping_data
GROUP BY gender ;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?


SELECT DISTINCT 
customer_id , 
purchase_amount , 
(SELECT AVG(purchase_amount) FROM sales.shopping_data) AS AvgAmount
FROM sales.shopping_data 
WHERE purchase_amount >=  (SELECT AVG(purchase_amount) FROM sales.shopping_data)
AND  discount_applied = 'YES' ;



-- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5 
Item_purchased ,
ROUND(AVG(review_rating) , 2) AS AvgRating
FROM sales.shopping_data
GROUP BY item_purchased 
ORDER BY AvgRating DESC;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.


SELECT 
 shipping_type, 
 AVG(purchase_amount) AvgAmount 
FROM sales.shopping_data
WHERE shipping_type IN ('Express' ,'Standard')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
subscription_status,
COUNT(customer_id) AS CustomersIncluded,
AVG(purchase_amount) AS AvgSpend ,
SUM(purchase_amount) AS TotalRevenue 
FROM sales.shopping_data
GROUP BY subscription_status
ORDER BY TotalRevenue ,AvgSpend  DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5 
item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0  END )/COUNT(*) , 2) AS discount_rate
FROM sales.shopping_data
GROUP BY  item_purchased 
ORDER BY discount_rate DESC;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH cte_segment AS (
SELECT customer_id , 
previous_purchases,
CASE 
	WHEN previous_purchases > 20 THEN 'Loyal'
	WHEN previous_purchases > 7 THEN 'Returning' 
	ELSE 'New'
END AS Segment
FROM sales.shopping_data)

SELECT 
segment , 
COUNT(Segment) AS SegmentCount
FROM cte_segment
GROUP BY Segment ; 

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
SELECT 
category ,
item_purchased,
COUNT(customer_id) As total_orders ,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) item_rank
FROM sales.shopping_data
GROUP BY category , item_purchased)

SELECT  
item_rank ,
category,
item_purchased ,
total_orders
FROM item_counts
WHERE item_rank <= 3 ;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
Count(customer_id) Repeat_Buyers ,
subscription_status 
FROM sales.shopping_data 
WHERE previous_purchases > 5 
GROUP BY subscription_status 

-- Q10. What is the revenue contribution of each age group?

SELECT 
age_group ,
SUM(previous_purchases) AS TotalRevenue ,
ROUND(
        100 * SUM(purchase_amount) /
        SUM(SUM(purchase_amount)) OVER (),
        2) AS RevenueContribution
FROM sales.shopping_data
GROUP BY age_group
ORDER BY TotalRevenue DESC ;
